---
- name: Disable unattended upgrades
  hosts: all
  become: true
  tasks:
    - name: Disable and stop unattended-upgrades service
      ansible.builtin.service:
        name: unattended-upgrades
        state: stopped
        enabled: no

- name: Update and upgrade packages on the system
  hosts: all
  become: true
  tasks:
    - name: Run apt update
      ansible.builtin.apt:
        update_cache: yes

- name: установка nginx и сопутствующих пакетов
  hosts: vm_1, vm_3, vm_4
  tasks:
    - name: Ensure packets is installed
      ansible.builtin.package:
        name:
          - nginx
          - php-fpm
          - php-pgsql
          - php-intl
          - php-gd
          - php-xml
          - php-mbstring
          - libpq-dev
          - python3-pip
          - acl
          - tcpflow
        state: present

- name: Install postgresql-client-14
  hosts: vm_3, vm_4
  tasks:
    - name: Ensure PostgreSQL is installed
      ansible.builtin.package:
        name: postgresql-client-14 
        state: present

- name: Install PostgreSQL
  hosts: vm_5, vm_6
  tasks:
    - name: Ensure PostgreSQL is installed
      ansible.builtin.package:
        name: postgresql
        state: present

- name: Install python3-pip, ACL
  hosts: vm_5
  tasks:
    - name: Ensure PostgreSQL is installed
      ansible.builtin.package:
        name:
          - python3-pip
          - acl
        state: present

- name: Перезапустить PostgreSQL
  hosts: vm_5 
  become: true
  tasks:
    - name: Перезапуск PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted

- name: Установка главной PG and user PG
  hosts: vm_5
  become: true
  vars:
    db_user: wikiuser
    db_password: 35795147
    db_name: my_wiki
  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Create db user
      community.postgresql.postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: "NOSUPERUSER,NOCREATEDB,LOGIN"
      become: true
      become_user: postgres

    - name: Create db
      community.postgresql.postgresql_db:
        state: present
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
      become: true
      become_user: postgres

- name: Замена postgresql.conf
  hosts: vm_5
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/postgresql.conf
        dest: /etc/postgresql/14/main/postgresql.conf

- name: Замена pg_hba.conf
  hosts: vm_5 
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/pg_hba.conf
        dest: /etc/postgresql/14/main/pg_hba.conf

- name: Перезапустить PostgreSQL
  hosts: vm_5 
  become: true
  tasks:
    - name: Перезапуск PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted

- name: Copy archive mediawiki to vm_3, vm_4
  hosts: vm_3, vm_4
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/wikidata.tgz
        dest: /home/ubuntu/wikidata.tgz

    - name: Extract wikidata.tgz to /var/www/mediawiki
      unarchive:
        src: /home/ubuntu/wikidata.tgz
        dest: /home/ubuntu/
        remote_src: yes

    - name: move directory /home/ubuntu/var/www/mediawiki to /var/www/mediawiki
      shell: mv /home/ubuntu/var/www/mediawiki  /var/www/mediawiki

- name: Установить wgServer = 'http://mediawiki'
  hosts: vm_3, vm_4
  become: yes
  tasks:
    - name: Получить внешний IP-адрес
      shell: curl -s https://api.ipify.org
      register: ip_address

    - name: Установить wgServer с полученным IP-адресом
      ansible.builtin.replace:
        path: /var/www/mediawiki/LocalSettings.php
        regexp: "(\\$wgServer\\s*=\\s*)'[^']*'\\s*;"
        replace: "\\1'http://{{ ip_address.stdout }}';"

- name: Copy dump mediawiki to vm_5
  hosts: vm_5
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/mywikidump.sql
        dest: /var/lib/postgresql/

- name: Restore PostgreSQL database on vm_5
  hosts: vm_5
  tasks:
    - name: Restore database
      become: true
      community.postgresql.postgresql_db:
        name: my_wiki
        state: restore
        db: my_wiki
        target: /var/lib/postgresql/mywikidump.sql
        login_user: wikiuser
        login_password: 35795147
          

- name: Создание конфига nginx-mediawiki
  hosts: vm_3, vm_4
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/mediawiki
        dest: /etc/nginx/sites-available/mediawiki


- name: Создать символьную ссылку
  hosts: vm_3, vm_4
  become: true
  tasks:
    - name: Создание символьной ссылки
      file:
        src: /etc/nginx/sites-available/mediawiki
        dest: /etc/nginx/sites-enabled/mediawiki
        state: link

- name: Удалить файл что бы не конфликтовали
  hosts: vm_3, vm_4
  become: true
  tasks:
    - name: Удаление файла
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
          
- name: Перезапустить nginx
  hosts: vm_3, vm_4
  become: true
  tasks:
    - name: Перезапуск nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: Замена конфига nginx proxy
  hosts: vm_1
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/nginxproxy.conf
        dest: /etc/nginx/nginx.conf

- name: собрать внешний айпи для vm_3
  hosts: vm_3
  become: yes
  tasks:
    - name: Получить внешний IP-адрес
      shell: curl -s https://api.ipify.org
      register: ip_address

    - name: записать полученный айпи в файл hosts
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: /home/shukinyure/ansible/hosts
        line: "192.168.10.8 {{ ip_address.stdout }}"  # Для vm_3

- name: собрать внешний айпи для vm_4
  hosts: vm_4
  become: yes
  tasks:
    - name: Получить внешний IP-адрес
      shell: curl -s https://api.ipify.org
      register: ip_address1

    - name: делаем алиас /etc/hosts
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: /home/shukinyure/ansible/hosts
        line: "192.168.10.4 {{ ip_address1.stdout }}"  # Для vm_4

- name: Замена etc/hosts
  hosts: vm_1
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/hosts
        dest: /etc/hosts

- name: Перезапустить nginx
  hosts: vm_1
  become: true
  tasks:
    - name: Перезапуск nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: Download and Extract zabbix
  hosts: vm_2
  tasks:
    - name: Download zabbix
      get_url:
        url: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.4+ubuntu22.04_all.deb
        dest: /home/zabbix-release_latest_7.4+ubuntu22.04_all.deb

- name: Install Zabbix package
  hosts: vm_2
  become: true
  tasks:
    - name: Inspect Zabbix package
      command: dpkg -i /home/zabbix-release_latest_7.4+ubuntu22.04_all.deb
      args:
        creates: /etc/zabbix/zabbix_server.conf

- name: Update and upgrade packages on the system
  hosts: vm_2
  become: true
  tasks:
    - name: Run apt update
      ansible.builtin.apt:
        update_cache: yes

- name: установка сопутствующих пакетов
  hosts: vm_2
  tasks:
    - name: Ensure packets is installed
      ansible.builtin.package:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - acl
          - python3-pip
          - postgresql
        state: present

- name: postgresql Playbook
  hosts: vm_2
  become: true
  vars:
    db_user: zabbix
    db_password: 35795147
    db_name: zabbix
  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
    - name: Create db user
      community.postgresql.postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: true
      become_user: postgres

    - name: Create db
      community.postgresql.postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: true
      become_user: postgres

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres

- name: Перезапустить PostgreSQL
  hosts: vm_2
  become: true
  tasks:
    - name: Перезапуск PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted


- name: Copy конфигурационного файла zabbix on vm_2
  hosts: vm_2
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/zabbix_server.conf
        dest: /etc/zabbix/

    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/nginx.conf
        dest: /etc/zabbix/

    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/zabbix.conf.php
        dest: /etc/zabbix/web/

    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/pg_hbazabbix.conf
        dest: /etc/postgresql/14/main/pg_hba.conf

- name: Перезапустить PostgreSQL
  hosts: vm_2
  become: true
  tasks:
    - name: Перезапуск PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted

- name: Copy dump zabbix to vm_2
  hosts: vm_2
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/zabbixdump.sql
        dest: /var/lib/postgresql/

- name: Restore PostgreSQL database on vm_2
  hosts: vm_2
  tasks:
    - name: Restore database
      become: true
      community.postgresql.postgresql_db:
        name: zabbix
        state: restore
        db: zabbix
        target: /var/lib/postgresql/zabbixdump.sql
        login_user: zabbix
        login_password: 35795147     

- name: Перезапустить Zabbix PHP
  hosts: vm_2
  become: true
  tasks:
    - name: Перезапуск Zabbix-server
      ansible.builtin.service:
        name: zabbix-server
        state: restarted

    - name: Перезапуск PHP8.1
      ansible.builtin.service:
        name: php8.1-fpm
        state: restarted

    - name: Перезапуск nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
