---
- name: Change listen_addresses in postgresql.conf
  hosts: vm_5
  become: true
  tasks:
    - name: Update listen_addresses setting
      ansible.builtin.lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        regexp: '^#?listen_addresses = .*'
        line: 'listen_addresses = "*"'
        state: present

