---
linux:  # Группа хостов
  children:  # Обозначение, что будет подгруппа хостов
    mediawiki:  # Имя подгруппы хостов
      hosts:  # Узлы группы
        vm_1:  # Имя машины
          ansible_host: 178.154.202.233
          your_variable: test
        vm_2:
          ansible_host: 158.160.114.158
          your_variable: nginx
    postgresql_servers:
      hosts:
        vm_3:
          ansible_host: 158.160.126.178
          your_variable: zabbix
        vm_4:
          ansible_host: 158.160.60.77
          your_variable: postgres1
        vm_5:
          ansible_host: 178.154.203.22
          your_variable: postgres2
        vm_6:
          ansible_host: 89.169.159.122
          your_variable: postgres3
  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: "ubuntu"
      # postgresql_user: "wikiuser"
      # postgresql_password: "35795147"
      # postgresql_db: "my_wiki"
    connection_protocol: ssh  # тип подключения
    ansible_become: true  # Становиться ли другим пользователем после подключения
