---
- name: Download and Extract zabbix
  hosts: vm_3 
  tasks:
    - name: Download zabbix
      get_url:
        url: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.4+ubuntu22.04_all.deb
        dest: /home/zabbix-release_latest_7.4+ubuntu22.04_all.deb

- name: Install Zabbix package
  hosts: vm_3
  become: true
  tasks:
    - name: Inspect Zabbix package
      command: dpkg -i /home/zabbix-release_latest_7.4+ubuntu22.04_all.deb
      args:
        creates: /etc/zabbix/zabbix_server.conf

- name: Update and upgrade packages on the system
  hosts: vm_3
  become: true
  tasks:
    - name: Run apt update
      ansible.builtin.apt:
        update_cache: yes

- name: установка сопутствующих пакетов
  hosts: vm_3
  tasks:
    - name: Ensure packets is installed
      ansible.builtin.package:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - acl
          - postgresql
        state: present

- name: postgresql Playbook
  hosts: vm_3
  become: true
  vars:
    db_user: zabbix
    db_password: 35795147
    db_name: zabbix
  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
    - name: Create db user
      community.postgresql.postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: true
      become_user: postgres

    - name: Create db
      community.postgresql.postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: true
      become_user: postgres

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres


- name: Перезапустить PostgreSQL
  hosts: vm_3 
  become: true
  tasks:
    - name: Перезапуск PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted

- name: Import Zabbix SQL schema
  hosts: vm_3
  become: true
  tasks:
    - name: Execute SQL import command
      shell: zcat /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix


- name: Замена конфига nginx zabbix
  hosts: vm_3
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/zabbixnginx.conf
        dest: /etc/zabbix/nginx.conf


- name: Замена конфига nginx zabbix
  hosts: vm_3
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/shukinyure/ansible/zabbix_server.conf
        dest: /etc/zabbix/zabbix_server.conf
         
- name: Перезапустить Zabbix PHP
  hosts: vm_3
  become: true
  tasks:
    - name: Перезапуск Zabbix-server
      ansible.builtin.service:
        name: zabbix-server
        state: restarted

    - name: Перезапуск PHP8.1
      ansible.builtin.service:
        name: php8.1-fpm
        state: restarted 
