---
linux:  # Группа хостов
  children:  # Обозначение, что будет подгруппа хостов
    mediawiki:  # Имя подгруппы хостов
      hosts:  # Узлы группы
        vm_1:  # Имя машины
          ansible_host: 158.160.122.58
          your_variable: test
        vm_2:
          ansible_host: 158.160.109.12
          your_variable: nginx
    postgresql_servers:
      hosts:
        vm_3:
          ansible_host: 158.160.116.100
          your_variable: zabbix
        vm_4:
          ansible_host: 51.250.80.59
          your_variable: postgres1
        vm_5:
          ansible_host: 158.160.125.241
          your_variable: postgres2
        vm_6:
          ansible_host: 51.250.93.255
          your_variable: postgres3
  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: "ubuntu"
      #    ansible_password: "qwerty"
    connection_protocol: ssh  # тип подключения
    ansible_become: true  # Становиться ли другим пользователем после подключения
